# Generated by Django 4.1 on 2024-07-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='site_detail/logo')),
                ('default_user_profile', models.ImageField(upload_to='', verbose_name='site_detail/profile')),
            ],
        ),
    ]
