# Generated by Django 4.1 on 2024-07-09 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_seriesmodel_moviemodel_age_alter_moviemodel_grade_and_more'),
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('movie', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.moviemodel')),
                ('series', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.seriesmodel')),
            ],
        ),
    ]
