# Generated by Django 4.1 on 2024-07-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_bannermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedetailmodel',
            name='blog_background',
            field=models.ImageField(default=1, upload_to='site_detail/background'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sitedetailmodel',
            name='default_user_profile',
            field=models.ImageField(upload_to='site_detail/profile'),
        ),
    ]
