# Generated by Django 4.1 on 2024-07-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_sitedetailmodel_blog_background_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='sitedetailmodel',
            name='privacy_background',
            field=models.ImageField(default=1, upload_to='site_detail/background'),
            preserve_default=False,
        ),
    ]
