# Generated by Django 4.1 on 2024-07-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_privacymodel_sitedetailmodel_privacy_background'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularQuestionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='sitedetailmodel',
            name='faq_background',
            field=models.ImageField(default=1, upload_to='site_detail/background'),
            preserve_default=False,
        ),
    ]
