# Generated by Django 4.1 on 2024-07-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_popularquestionsmodel_sitedetailmodel_faq_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedetailmodel',
            name='about_us_background',
            field=models.ImageField(default=1, upload_to='site_detail/background'),
            preserve_default=False,
        ),
    ]
