# Generated by Django 4.1 on 2024-07-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_sitedetailmodel_address_sitedetailmodel_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('family_name', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('seen_by_admin', models.BooleanField(default=False)),
                ('admin_message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
