# Generated by Django 4.1 on 2024-07-08 12:21

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='birth_date',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True),
        ),
    ]
