# Generated by Django 4.1 on 2024-07-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usermodel_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fullname',
            field=models.CharField(default='No Name', max_length=150, verbose_name='نام'),
        ),
    ]
