# Generated by Django 4.1 on 2024-07-08 11:42

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='notification/image')),
                ('description', models.TextField(blank=True, null=True)),
                ('date', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
            ],
        ),
    ]
