# Generated by Django 4.1 on 2024-07-08 11:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmodel',
            name='user',
            field=models.ManyToManyField(related_name='user_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
