# Generated by Django 4.1 on 2024-07-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000)),
                ('url', models.SlugField(allow_unicode=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000)),
                ('url', models.SlugField(allow_unicode=True)),
                ('image', models.ImageField(upload_to='category/image')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000)),
                ('url', models.SlugField(allow_unicode=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000)),
                ('url', models.SlugField(allow_unicode=True)),
                ('image', models.ImageField(upload_to='movie/image')),
                ('trailer', models.FileField(upload_to='movie/trailer')),
                ('video', models.FileField(upload_to='movie/video')),
                ('description', models.TextField()),
                ('time', models.PositiveIntegerField()),
                ('grade', models.PositiveIntegerField()),
                ('actors', models.ManyToManyField(related_name='actor_movies', to='movie.actormodel')),
                ('category', models.ManyToManyField(related_name='category_movies', to='movie.categorymodel')),
                ('tags', models.ManyToManyField(related_name='tag_movies', to='movie.tagmodel')),
            ],
        ),
    ]
