# Generated by Django 4.1 on 2024-07-09 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000)),
                ('grade', models.FloatField()),
                ('actors', models.ManyToManyField(related_name='actor_serials', to='movie.actormodel')),
            ],
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='age',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='grade',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='SeriesSeasonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000)),
                ('description', models.TextField()),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movie.seriesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='SerialPartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000)),
                ('video', models.FileField(upload_to='serial/video')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='serial/image')),
                ('trailer', models.FileField(upload_to='serial/trailer')),
                ('time', models.PositiveIntegerField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.seriesseasonmodel')),
                ('tags', models.ManyToManyField(related_name='tag_serials', to='movie.tagmodel')),
            ],
        ),
    ]
