# Generated by Django 4.1 on 2024-07-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_seriesmodel_moviemodel_age_alter_moviemodel_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='seriesmodel',
            name='category',
            field=models.ManyToManyField(related_name='category_series', to='movie.categorymodel'),
        ),
    ]
