# Generated by Django 4.1 on 2024-07-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_categorymodel_active_seriesmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemodel',
            name='time',
            field=models.TimeField(),
        ),
    ]
